#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: 2026年 09月 12日 星期六 22:13:55 CST

wallr quit >/dev/null 2>&1 || true
pkill -x -9 phonto 2>/dev/null || true
pkill -x -9 mpvpaper 2>/dev/null || true

case "wallr" in
    wallr)
        wallr set "/home/xibie/Pictures/Wallpapers/yeqi.mp4" --mode fill --no-theme >/dev/null 2>&1 &
        ;;
    phonto)
        phonto "/home/xibie/Pictures/Wallpapers/yeqi.mp4" --layer background >/dev/null 2>&1 &
        ;;
    mpvpaper)
        while IFS= read -r monitor; do
            mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/xibie/Pictures/Wallpapers/yeqi.mp4" &
            sleep 0.1
        done < <(hyprctl monitors -j | jq -r '.[] | .name')
        ;;
esac
