#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: 2026年 09月 12日 星期六 01:41:15 CST

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/xibie/Pictures/Wallpapers/yeqi.mp4" &
    sleep 0.1
done
