[colors.primary]
background = '#191112'
foreground = '#f0dee0'

[colors.selection]
text = '#f0dee0'
background = '#713340'

[colors.cursor]
text = '#191112'
cursor = '#ffb2be'

[colors.normal]
black   = '#191112'
red     = '#ff7275'
green   = '#9dff7f'
yellow  = '#ffe272'
blue    = '#f29aa8'
magenta = '#713340'
cyan    = '#ffb2be'
white   = '#ffeff2'

[colors.bright]
black   = '#484042'
red     = '#ff9fa1'
green   = '#baffa5'
yellow  = '#ffeda5'
blue    = '#ffbdc7'
magenta = '#ffc9d1'
cyan    = '#ffdce1'
white   = '#fff8f9'
